### PR TITLE
Version: 0.1.0 and indicating Python 3.

### PR DESCRIPTION
**Pull request by bernhardreiter**
Given a few changes since version 0.0.5 was initially used,
go to 0.1.0 and indicate that pyxarf shall work on python3, too.

We are using pyxarf in https://github.com/Intevation/intelmq-mailgen 
with python3 only. In order to indicate the dependencies clearly it would be nice
to use a new version number.  The published https://pypi.python.org/pypi/pyxarf/0.0.5
probably does not have the changes. My suggestion is v0.1.0 because pyxarf is used
in a real setting so 0.1.0 for the switch to python3 compatibility seems okay.

### CODE REVIEW

**Comment by bernhardreiter** [comment]
Ping. @tknecht, any chance to get this merged. :)

**Comment by bernhardreiter** [comment]
@tknecht ping?

**Comment by FrederikP** [comment]
Hi, sorry for the late response.
I'll have a look at this. According to https://github.com/xarf/python-xarf/issues/6 there are some issues with python 3 compatibilty, so need to check that first.

**Comment by bernhardreiter** [comment]
@FrederikP thanks for looking into this!

**Comment by FrederikP** [comment]
Hi, I worked on making it python 3 compatible and fixed some other issues. 
The release version is indeed 0.1.0 and I also tested and indicated python 3 support.
Closing this PR.

Please open an issue if you there are problems with this release.

Thanks for your PR.

**Comment by bernhardreiter** [comment]
@FrederikP thanks for the improvements and releasing version 0.1.0! And for pyxarf in the first place.

**Pull request closed without merging**
